### ISSUE TITLE
Fan starts on reverse direction

### ISSUE THREAD

**Issue by gsdovali** [NicoIIT/esphome-components#2]
Since the last update, every time I start my fan, direction is reverse, however it shows forward on HA, I have to set reverse and forward to get it corrected.

**Comment by NicoIIT** [comment]
I added a feature to force the send of direction at Fan startup, but is should not have this consequence, it is supposed to align the  direction state between HA and the Fan, but it seem it may not work the proper way with your fan...
Could you please tell me which encoding / variant you are using ?
FYI you can deactivate the feature with option `forced_refresh_on_start: false` at Fan level, see the doc.

**Comment by gsdovali** [comment]
It worked with forced_refresh_on_start: false
Enconding used is fanlamp_pro V3

**Comment by NicoIIT** [comment]
OK good news!
Still it does not explain why this option is not working for you. May I ask you this info if possible?
* Your config file
* The DEBUG logs when the problem is occurring

Thanks!

**Comment by gsdovali** [comment]
Can you let me know how to get debug logs?

**Comment by gsdovali** [comment]
[logs_ventilador-recamara-principal_run.txt](https://github.com/user-attachments/files/16742007/logs_ventilador-recamara-principal_run.txt)

This is the log file
[ventilador-recamara-principal.txt](https://github.com/user-attachments/files/16742011/ventilador-recamara-principal.txt)

**Comment by NicoIIT** [comment]
Thanks for the logs!

From what I see the app is working as it should, I would say your fan is "buggy" and interprets the direction "Forward" command as a direction "toggle" command, meaning when it receives such command it switches direction instead of ignoring it in case it is already in the "forward" direction. 

You should be able to see this buggy behavior from the phone app already if you are using it: pressing several time the "direction forward" button should make the fan change direction, whereas there is also a "direction reverse" button.

If it is the case there is nothing more to do than adding the `forced_refresh_on_start: false` option and we can close this issue ! If more users experience the same issue I can deactivate this option by default.

**Comment by gsdovali** [comment]
Ok, I've set the option to false. 
I am not able to reproduce the issue from my remote or cell, as they where unpaired when paired the esp32 board; is there a way to pair both esp32 and remote?

**Comment by NicoIIT** [comment]
> I am not able to reproduce the issue from my remote or cell, as they where unpaired when paired the esp32 board; is there a way to pair both esp32 and remote?

Depends on the Fan, most of them supports a remote and a phone app at the same time, so the esp32 would replace one of them (probably the phone app).

In any case I am working on capturing the messages sent by the remote / phone app and in a second time have them controlling the esp32 directly.

If you want to help you can try to setup the [Capture](https://github.com/NicoIIT/esphome-components/blob/main/components/ble_adv_controller/CUSTOM.md#capturing-advertising-messages) of the BLE ADV messages, and send me the DEBUG logs when the remote is used, for example to switch ON the light (no need to pair, just press the remote button).

Thanks!

**Comment by gsdovali** [comment]
Probably not a buggy device, looking at the remote, the forward/reverse button is the same, so probably it just toggle a switch.
![PXL_20240826_053431613](https://github.com/user-attachments/assets/0f428979-9d48-4c73-8be0-de519e7f5b56)
BTW, my remote is working, batteries were removed.
I'll take a look at capture info and send you what you requested

**Comment by NicoIIT** [comment]
> BTW, my remote is working, batteries were removed.

😄 

For the toggle direction button, let's use the standard call center answer: "It's not a bug, it's a feature", but a feature that does not work with the phone app. I may add an option for this to consider the Fan direction / oscillation as toggles, or change the recently added option to a "fan_resets_direction_at_start" and then avoid sending "direction change" command when not needed which would comply with your fan behavior and the previously open feature request.

If you manage to capture the messages sent by your remote, I would also appreciate the logs when:
* the "K+" is pressed
* the "K-" is pressed
* the "F/R" is pressed, and pressed a second time, to confirm what we saw (on my remote it sends 2 different commands)
* the "Oscillation" is pressed, and pressed a second time, to confirm it has the same behavior
* the "ON/OFF" is pressed, and pressed a second time, to see if same as previous or a different behavior (on my remote, it sends 2 different commands)

Thanks!

**Comment by gsdovali** [comment]
Ok, I'll try the capture, but should I add the capture code to the same yaml file? I'm really new to esphome. Still learning.

**Comment by gsdovali** [comment]
Ok, doing it and sending the capture logs... Should I set "forced_refresh_on_start: true" or can leave it as false?

**Comment by gsdovali** [comment]
Ok, adding capture logs.
[logs_ventilador-recamara-principal_logs.txt](https://github.com/user-attachments/files/16750211/logs_ventilador-recamara-principal_logs.txt)

**Comment by gsdovali** [comment]
Thanks, I am closing this and keep waiting for any updates on your component

**Comment by gsdovali** [comment]
Hey just to let you know, I modified my fan code yaml and added automation "on_turn_on" to set direction to forward and set "forced_refresh_on_start1: true"  It fixed my problem. I always use my fan on forward direction.
Thanks for you help

**Comment by NicoIIT** [comment]
FYI, I changed the default value to `false` for this feature.
