### ISSUE TITLE
Component ble_adv_handler cannot be used together with component esp32_ble_tracker

### ISSUE THREAD

**Issue by jdgiddings** [NicoIIT/esphome-components#7]
![image](https://github.com/user-attachments/assets/e0d6c539-b025-49f7-93e6-368635c0e17a)

`Component ble_adv_handler cannot be used together with component esp32_ble_tracker.`

I'm getting this error trying to follow the steps in https://github.com/NicoIIT/esphome-components/tree/main/components/ble_adv_controller#setup-without-pairing

Any advice? The code is directly copy-pasted from the docs

**Comment by NicoIIT** [comment]
Hello @jdgiddings, this one is quite easy to solve 😄: you are using the `dev` branch software but referring to the `main` branch documentation. Try the [dev](https://github.com/NicoIIT/esphome-components/tree/dev/components/ble_adv_controller#setup-without-pairing) doc for the setup without pairing, or the [dev doc entry point](https://github.com/NicoIIT/esphome-components/blob/dev/README.md).

**Comment by jdgiddings** [comment]
Well... that's embarrassing. Thanks @NicoIIT !
